# Generated by Django 4.2.7 on 2024-01-05 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopFront", "0003_customer_membership"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="slug",
            field=models.SlugField(null=True),
        ),
    ]
