# Generated by Django 4.2.7 on 2024-01-05 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopFront", "0004_alter_product_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="collection",
        ),
        migrations.DeleteModel(
            name="Collection",
        ),
    ]
