# Generated by Django 4.2.7 on 2024-01-05 13:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopFront", "0005_remove_product_collection_delete_collection"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
