# Generated by Django 4.2.7 on 2024-01-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopFront", "0007_order_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("COMPLETE", "COMPLETE"),
                    ("FAILED", "FAILED"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
