# Generated by Django 4.2.7 on 2024-05-05 04:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopFront", "0009_order_note_alter_customer_membership"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[("Hot", "Hot"), ("Cold", "Cold")], max_length=200, null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(to="shopFront.tag"),
        ),
    ]
