# Generated by Django 4.2.7 on 2024-05-05 04:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("shopFront", "0010_tag_product_category_product_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tag",
        ),
    ]
