# Generated by Django 4.2.7 on 2024-05-05 06:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopFront", "0011_remove_product_tags_delete_tag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="promotions",
        ),
        migrations.AddField(
            model_name="product",
            name="promotions",
            field=models.CharField(
                choices=[
                    ("Eid al-Fitr", "Eid al-Fitr"),
                    ("Christmas", "Christmas"),
                    ("Halloween", "Halloween"),
                ],
                max_length=200,
                null=True,
            ),
        ),
    ]
