# Generated by Django 4.2.7 on 2024-05-06 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopFront", "0013_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="profile_pic",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
