# Generated by Django 4.2.7 on 2024-05-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopFront", "0015_alter_customer_profile_pic_alter_customer_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer",
            old_name="first_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="customer",
            name="profile_pic",
            field=models.FileField(
                blank=True, default="profile1.png", null=True, upload_to=""
            ),
        ),
    ]
