# Generated by Django 4.2.7 on 2024-05-07 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shopFront", "0016_rename_first_name_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
